version: "3.6"

services:
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - /home/douglas/Documentos/work/workspace/lab/version-management-sample/nexus-volume:/nexus-data